ExUnit.start(exclude: [:integration], capture_log: true)
Ecto.Adapters.SQL.Sandbox.mode(Zaq.Repo, :manual)
Registry.start_link(keys: :unique, name: Zaq.Engine.Workflows.RunRegistry)
Logger.put_module_level(Postgrex.Protocol, :none)
Logger.put_module_level(Task.Supervised, :none)
