import Config

# Configure your database
# Database name is derived from the current git branch so each worktree gets isolation automatically.
dev_db_name =
  case System.cmd("git", ["branch", "--show-current"], stderr_to_stdout: false) do
    {branch, 0} ->
      slug = branch |> String.trim() |> String.downcase() |> String.replace(~r/[^a-z0-9]+/, "_")
      if slug == "", do: "zaq_dev", else: "zaq_#{slug}"

    _ ->
      "zaq_dev"
  end

config :zaq, Zaq.Repo,
  types: Zaq.PostgrexTypes,
  username: System.get_env("DB_USER", "postgres"),
  password: System.get_env("DB_PASSWORD", "postgres"),
  hostname: System.get_env("DB_HOST", "localhost"),
  database: dev_db_name,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :zaq, roles: [:bo, :agent, :ingestion, :channels, :engine]
# config :zaq, roles: [:bo]

# In a worktree, .git is a file (gitdir pointer), not a directory.
# Worktrees must not overwrite the shared hooks in .git/hooks/ — only the main repo installs them.
in_worktree? = not File.dir?(Path.join([__DIR__, "..", ".git"]))

config :git_hooks,
  auto_install: not in_worktree?,
  project_path: Path.expand("..", __DIR__),
  verbose: true,
  hooks: [
    pre_commit: [
      tasks: [
        {:mix_task, :quality}
      ]
    ],
    commit_msg: [
      tasks: [
        # include_hook_args passes git's $1 (the COMMIT_EDITMSG path) to git_ops.
        # Git passes a relative path for the main repo (.git/COMMIT_EDITMSG) and an
        # absolute path for worktrees — git_ops handles both cases correctly.
        {:cmd, "mix git_ops.check_message", include_hook_args: true}
      ]
    ],
    pre_push: [
      tasks: [
        {:mix_task, :format, ["--check-formatted"]}
      ]
    ]
  ]

config :git_ops,
  mix_project: Zaq.MixProject,
  changelog_file: "CHANGELOG.md",
  repository_url: "https://github.com/www-zaq-ai/zaq",
  manage_mix_version?: true,
  version_tag_prefix: "v",
  types: [
    feat: [header: "Features"],
    fix: [header: "Bug Fixes"],
    perf: [header: "Performance"],
    refactor: [header: "Refactoring"],
    docs: [hidden?: true],
    test: [hidden?: true],
    chore: [hidden?: true],
    ci: [hidden?: true]
  ]

config :zaq, :base_url, "http://localhost:4000"

config :zaq, Zaq.System.SecretConfig,
  encryption_key: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=",
  key_id: "v1"

config :zaq, Zaq.Ingestion,
  base_path: "priv/documents",
  volumes: %{
    "documents" => "priv/documents",
    "archives" => "priv/archives"
  }

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :zaq, ZaqWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LQsyDCz226Q0u9cBQuDXhOBf09HwGPydTPfHPtYjMEGhPXZkXlalT73FrQ+fj5hq",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:zaq, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:zaq, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :zaq, ZaqWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/zaq_web/router\.ex$"E,
      ~r"lib/zaq_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :zaq, dev_routes: true

config :zaq, :figma_capture_enabled, true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# config :zaq, :jido_telemetry_bridge, include_llm_deltas: true

# Imported last so per-worktree overrides (database name, port, etc.) win over all defaults above.
if File.exists?("config/dev.secret.exs"), do: import_config("dev.secret.exs")
