import Config

config :zaq, :secure_session_cookie, true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :zaq, ZaqWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force HTTPS in production and set the Strict-Transport-Security (HSTS) header.
# The TLS reverse proxy must overwrite X-Forwarded-Proto; restrict backend access
# to that proxy. See README's production HTTPS guide.
# Note `:force_ssl` is required to be set at compile-time.
config :zaq, ZaqWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [hosts: ["localhost", "127.0.0.1"]]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
